name: rohme
description: The Rapid Object orientated Hardware Modelling Environment, an environment for the modelling of digital Systems using the Dart programming Language.
version: 1.1.2

environment:
  sdk: ^3.2.4

dependencies:
  args: ^2.4.2
  clock: ^1.1.0
  collection: ^1.15.0
  rohd:
    path: ../../rohd

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

repository:
  https://github.com/AdamRose66/rohme
