name: rohme
description: Upgrade to Register
version: 1.0.1

environment:
  sdk: ^3.2.4

dependencies:
  fake_async: ^1.3.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

repository:
  https://github.com/AdamRose66/rohme
