name: rohme
description: Upgrade to Register
version: 1.1.0

environment:
  sdk: ^3.2.4

dependencies:
  clock: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

repository:
  https://github.com/AdamRose66/rohme
